language: bash
addons:
  apt:
    sources:
    - debian-sid    # Grab ShellCheck from the Debian repo
    packages:
    - shellcheck
    - bats

script:
 - shellcheck -x $(grep -rl '^#!/.*sh' ./*)
 - bash -c 'cd tests && bats --tap *'
