language: bash
addons:
  apt:
    sources:
    - debian-sid    # Grab ShellCheck from the Debian repo
    packages:
    - shellcheck

script:
 - bash -c 'shopt -s globstar; shellcheck -x **/*.{sh,bash}'
