#!/bin/bash
##====================================================
## Little helper script to start a docker jupyter
## instance listening on a free port.
##====================================================
current_port=8888
while [ 'true' ]
do
  nc -z localhost $current_port &> /dev/null
  if [ $? -eq 1 ]
  then
    break
  fi

  current_port=$((current_port + 1))
done

echo "docker jupyter running on http://localhost:$current_port/"
docker run -e GRANT_SUDO=yes --user root -d -p $current_port:8888 -v "$(pwd)":/home/jovyan/work jupyter/datascience-notebook
