#!/bin/bash
function usage() {
  cat <<EOF
Usage: $(basename "$0") [-h]

Starts a docker jupyter/datascience-notebook with working directory mounted as volume.

Options:
  --help, -h      shows this message
EOF
}

[ "$#" -gt 0 ] && usage && exit 0

default_port=8888
. nextfreeport
target_port=$(nextfreeport $default_port)

docker run -e GRANT_SUDO=yes --user root -d -p "$target_port":$default_port \
  -v "$(pwd)":/home/jovyan/work jupyter/datascience-notebook && \
  echo "docker jupyter running on http://localhost:$target_port/"
