#!/bin/bash
function usage() {
  cat <<EOF
Usage: $(basename "$0") [-h]

Starts a docker jupyter/datascience-notebook with working directory mounted as volume.

Options:
  --help, -h      shows this message
EOF
}

[ "$#" -gt 0 ] && usage && exit 0

default_port=8888
. nextfreeport
target_port=$(nextfreeport $default_port)
token=$(date +%s | shasum | awk '{ print $1}')

url="http://localhost:$target_port/?token=$token"

docker run -e GRANT_SUDO=yes --user root -d -p "$target_port":$default_port \
  -v "$(pwd)":/home/jovyan/work jupyter/datascience-notebook \
  start-notebook.sh --NotebookApp.token="$token" && \
  echo -e "Jupyter notebook server is running. Open in browser:
  $url"

while ! curl -s "$url"
do
  ((c++)) && ((c==10)) && break
  sleep 1
done

if [ "$(uname)" == "Darwin" ]; then
    open "$url"
elif [[ "$(uname)" == "Linux" ]]; then
    xdg-open "$url"
fi
