#!/bin/bash
function usage() {
  cat <<EOF
Usage: $(basename "$0") [-h]

Starts a docker rocker/shiny server with working directory mounted as volume.

Options:
  --help, -h      shows this message
EOF
}

[ "$#" -gt 0 ] && usage && exit 0

default_port=3838
. nextfreeport
target_port=$(nextfreeport $default_port)

docker run -d -p "$target_port":$default_port  -v "$(pwd)":/srv/shiny-server/  rocker/shiny
echo "docker shiny running on http://localhost:$target_port/"
