#!/bin/bash
# shellcheck disable=SC2086
#===================================================================================================
# The script stores aliases in a user specific directory. In order to automatically load them, add
# the following to your '/etc/bashrc' (or os equivalent):
#
#	if [ -f ~/.bash_aliases ]; then
#   . ~/.bash_aliases
#	fi
#
# The script always uses the current working directory as the new alias target.
#===================================================================================================
function usage() {
  cat <<EOF
Usage: $(basename "$0") [-arph] alias

Creates an alias switching into the current working directory.

Options:
  --add, -a       adds a new alias with the given name
  --remove, -r    removes alias with the given name
  --print, -p     print all existing aliases
  --help, -h      shows this message
EOF
}

function add_alias() {
  name=$1
  cmd="alias $name='cd $(pwd)'"
  result=$(grep -c "alias $name" $bash_aliases)
  if [ $result -eq 0 ];
  then
    echo "$cmd" >> $bash_aliases
  else
    echo "there is already an alias with the name $name"
  fi;
}

function remove_alias() {
  name=$1
  result=$(grep -c "alias $name" $bash_aliases)
  if [ $result -ne 0 ];
  then
    sed '/alias '$name'/d' $bash_aliases > $bash_tmp
    mv $bash_tmp $bash_aliases
    echo "Please restart your shell."
  fi;
}

bash_aliases="${HOME}/.bash_aliases"
bash_tmp="${HOME}/.bash_tmp"
case $1 in
  --add|-a)
    shift
    add_alias $1
    ;;
  --remove|-r)
    shift
    remove_alias $1
    ;;
  --print|-p)
    cat $bash_aliases
    ;;
  --help|-h)
    usage
    ;;
  *)
    add_alias $1
esac

sort $bash_aliases -o $bash_aliases
# shellcheck disable=SC2059,SC1091
source /etc/bashrc
