#!/bin/bash
# shellcheck disable=SC2086
#===================================================================================================
# The script stores aliases in a user specific directory. In order to automatically load them, add
# the following to your '/etc/bashrc' (or os equivalent):
#
#	if [ -f ~/.pathalias ]; then
#   . ~/.pathalias
#	fi
#
# The script always uses the current working directory as the new alias target.
#===================================================================================================
function usage() {
  cat <<EOF
Usage: $(basename "$0") [-arph] alias

Creates an alias switching into the current working directory.

Options:
  --add, -a       adds a new alias with the given name
  --remove, -r    removes alias with the given name
  --print, -p     print all existing aliases
  --help, -h      shows this message
EOF
}

function add_alias() {
  name=$1
  if command -v $name &> /dev/null; then
    echo "A command named '$name' already exist."
    exit 1;
  fi;

  alias_count=$(grep -c "alias $name" $bash_aliases)
  if [ $alias_count -ne 0 ]; then
    echo "Alias '$name' already exist."
    exit 1;
  fi;

  echo "alias $name='cd $(pwd)'" >> $bash_aliases
}

function remove_alias() {
  name=$1
  alias_count=$(grep -c "alias $name" $bash_aliases)
  if [ $alias_count -ne 0 ]; then
    sed '/alias '$name'/d' $bash_aliases > $bash_tmp
    mv $bash_tmp $bash_aliases
    echo "Please restart your shell."
  fi;
}

bash_aliases="${HOME}/.pathalias"
bash_tmp="${HOME}/.bash_tmp"
case $1 in
  --add|-a)
    shift
    add_alias $1
    ;;
  --remove|-r)
    shift
    remove_alias $1
    ;;
  --print|-p)
    cat $bash_aliases
    ;;
  --help|-h)
    usage
    ;;
  *)
    add_alias $1
esac

sort $bash_aliases -o $bash_aliases
# shellcheck source=/dev/null
source $bash_aliases
