#!/bin/bash
# shellcheck disable=SC2086
#===================================================================================================
# The script reads svnignore properties from files located in svnignore.d. Each file in this
# directory represents a proplist. This script is to be called with the name of this proplist.
#
# Create a new file in svnignore.d in order to add a new proplist.
#===================================================================================================
function usage() {
  cat <<EOF
Uage: $(basename $0) [-ah] [proplist ...]

Ignore a set of commonly unwanted files from svn version control.

Options:
  --append, -a    append proplist to current set of ignores
  --help, -h      shows this message

Proplists:
  tex             tex files
  java            java build files
  cpp             qt project files
  cs              visual studio project files
  xc              xcode project files
EOF
}

dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
config=$dir/svnignore.d

tmpdir=$(mktemp -d)
trap 'rm -rf $tmpdir' EXIT

append=false
ignore_set=/dev/null
while [ $# -gt 0 ]
do
  case "$1" in
    --append|-a)
    append=true;;
    -*)
    usage
    exit 1;;
    *)
    if [ -e $config/$1 ]
    then
      ignore_set="${ignore_set} $config/$1"
    else
      echo >&2 "no such ignore propset: $1"
      exit 1
    fi
    ;;
  esac

  shift
done

cat $ignore_set >> $tmpdir/tmp.ignore

if [ "$append" = true ];
then
  svn proplist -v | grep -vE 'ignore|Properties' | perl -lape 's/\s+//sg' > $tmpdir/current.ignore
  cat $tmpdir/tmp.ignore $tmpdir/current.ignore | sort | uniq > $tmpdir/tmp.ignore.formatted
  mv $tmpdir/tmp.ignore.formatted $tmpdir/tmp.ignore
fi

svn propset svn:ignore -F $tmpdir/tmp.ignore . --recursive
