#!/bin/bash
##====================================================
## Toggles view state of desktop icons.
##====================================================
show="$(defaults read com.apple.finder CreateDesktop)"

if [ "$show" = true ]
then
	show=false
	echo "hide desktop"
else
	show=true
	echo "show desktop"
fi

defaults write com.apple.finder CreateDesktop $show; killall Finder
