#!/bin/bash
##====================================================
## Toggles view state of desktop icons.
##====================================================
show="$(defaults read com.apple.finder CreateDesktop 2>/dev/null)"

#$? -eq 1 in case CreateDesktop is not set, yet
if [ $? -eq 1 ] || [ "$show" = true ]
then
  show=false
  echo "hide desktop"
else
  show=true
  echo "show desktop"
fi

defaults write com.apple.finder CreateDesktop $show; killall Finder
